---
version: '3'
services:
  composer:
    image: herloct/composer:1.3.2-php7.1
    volumes:
      - .:/project
      - ./writables/composer:/composer/cache

  codecept:
    image: php:7.1.1-alpine
    working_dir: /project
    entrypoint:
      - php
      - vendor/bin/codecept
    volumes:
      - .:/project
